# Generated by Django 5.2.1 on 2025-05-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reminder_type', models.CharField(choices=[('health', 'Health'), ('meeting', 'Meeting'), ('birthday', 'Birthday'), ('other', 'Other')], max_length=50)),
            ],
        ),
    ]
